{{- if or .Values.clusterPolicies .Values.policies }}
{{- range $name, $cp := .Values.clusterPolicies }}
---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ $name | quote }}
  labels:
    app.kubernetes.io/managed-by: argocd-render
    {{- with $cp.labels }}
{{ toYaml . | indent 4 }}
    {{- end }}
  {{- with $cp.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
{{ toYaml $cp.spec | indent 2 }}
{{- end }}

{{- range $name, $p := .Values.policies }}
---
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: {{ $name | quote }}
  namespace: {{ $p.namespace | default "default" | quote }}
  labels:
    app.kubernetes.io/managed-by: argocd-render
    {{- with $p.labels }}
{{ toYaml . | indent 4 }}
    {{- end }}
  {{- with $p.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
{{ toYaml $p.spec | indent 2 }}
{{- end }}
{{- end }}
